/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.ResumeCatalog;
import Data.Resume;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author yyneu
 */
public class createJPanel extends javax.swing.JPanel {
private ResumeCatalog rc;
private String name;
private String sex; 
private String status;
private String nationality;
private String ageText;
private String workYearText;
private String java="";
private String c="";
private String cPlus="";
private String python="";
private String program;
    /**
     * Creates new form createJPanel
     */
    public createJPanel(ResumeCatalog rc) {
        initComponents();
        this.rc = rc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        btnGroupStatus = new javax.swing.ButtonGroup();
        btnGroupNationality = new javax.swing.ButtonGroup();
        btnGroupProgram = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        affiliationLabel = new javax.swing.JLabel();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        careerObjectiveStatementTextArea = new javax.swing.JTextArea();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        streetli1Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        streetln1TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        streetln2Label = new javax.swing.JLabel();
        EducationLabel = new javax.swing.JLabel();
        degree2Label = new javax.swing.JLabel();
        degreeDate1Label = new javax.swing.JLabel();
        degree1Label = new javax.swing.JLabel();
        degree1TextField = new javax.swing.JTextField();
        degreeDate1TextField = new javax.swing.JTextField();
        degree2TextField = new javax.swing.JTextField();
        degreeDate2TextField = new javax.swing.JTextField();
        degreeDate2Label = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        majorTextField = new javax.swing.JTextField();
        workYearLabel = new javax.swing.JLabel();
        workYearTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        pictureLabel1 = new javax.swing.JLabel();
        careerObjectiveStatementLabel1 = new javax.swing.JLabel();
        btnRadioMale = new javax.swing.JRadioButton();
        btnRadioFemale = new javax.swing.JRadioButton();
        btnRadioCitizen = new javax.swing.JRadioButton();
        btnRadioInternational = new javax.swing.JRadioButton();
        statusLabel = new javax.swing.JLabel();
        btnRadioGraduate = new javax.swing.JRadioButton();
        btnRadioInProgress = new javax.swing.JRadioButton();
        schoolLabel = new javax.swing.JLabel();
        javaCheckBox = new javax.swing.JCheckBox();
        cPlusCheckBox = new javax.swing.JCheckBox();
        pythonCheckBox = new javax.swing.JCheckBox();
        cCheckBox = new javax.swing.JCheckBox();
        programLabel = new javax.swing.JLabel();

        setAutoscrolls(true);

        jPanel1.setToolTipText("Resume Create");
        jPanel1.setAutoscrolls(true);

        firstNameLabel.setText("Firstname:");

        LastNameLabel.setText("Lastname:");

        sexLabel.setText("Sex:");

        ageLabel.setText("Age:");

        affiliationLabel.setText("Affiliation:");

        pictureLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pictureLabel.setText("Picture:");

        careerObjectiveStatementTextArea.setColumns(10);
        careerObjectiveStatementTextArea.setLineWrap(true);
        careerObjectiveStatementTextArea.setRows(20);
        careerObjectiveStatementTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(careerObjectiveStatementTextArea);

        streetli1Label.setText("Streetln1:");

        cityLabel.setText("City:");

        countryLabel.setText("Country:");

        adressLabel.setText("Address:");

        dobLabel.setText("DOB:");

        streetln2Label.setText("Streeln2:");

        EducationLabel.setText("Education:");

        degree2Label.setText("degree2:");

        degreeDate1Label.setText("degreeDate1:");

        degree1Label.setText("degree1:");

        degreeDate2Label.setText("degreeDate2:");

        majorLabel.setText("Major:");

        workYearLabel.setText("WorkYear:");

        createButton.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        createButton.setText("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        pictureLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/default.jpg"))); // NOI18N

        careerObjectiveStatementLabel1.setText("CareerObjevtiveStatement:");

        btnGroupSex.add(btnRadioMale);
        btnRadioMale.setText("male");
        btnRadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioMaleActionPerformed(evt);
            }
        });

        btnGroupSex.add(btnRadioFemale);
        btnRadioFemale.setText("female");
        btnRadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioFemaleActionPerformed(evt);
            }
        });

        btnGroupStatus.add(btnRadioCitizen);
        btnRadioCitizen.setText("citizen");
        btnRadioCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioCitizenActionPerformed(evt);
            }
        });

        btnGroupStatus.add(btnRadioInternational);
        btnRadioInternational.setText("international");
        btnRadioInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioInternationalActionPerformed(evt);
            }
        });

        statusLabel.setText("Status:");

        btnGroupNationality.add(btnRadioGraduate);
        btnRadioGraduate.setText("graduate");
        btnRadioGraduate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioGraduateActionPerformed(evt);
            }
        });

        btnGroupNationality.add(btnRadioInProgress);
        btnRadioInProgress.setText("in progress");
        btnRadioInProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioInProgressActionPerformed(evt);
            }
        });

        schoolLabel.setText("School:");

        javaCheckBox.setText("java");
        javaCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                javaCheckBoxStateChanged(evt);
            }
        });

        cPlusCheckBox.setText("c++");
        cPlusCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cPlusCheckBoxStateChanged(evt);
            }
        });

        pythonCheckBox.setText("python");
        pythonCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pythonCheckBoxStateChanged(evt);
            }
        });

        cCheckBox.setText("c");
        cCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cCheckBoxStateChanged(evt);
            }
        });

        programLabel.setText("Programming Skills");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(careerObjectiveStatementLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexLabel)
                                    .addComponent(affiliationLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(LastNameLabel)
                                    .addComponent(workYearLabel)
                                    .addComponent(majorLabel)
                                    .addComponent(dobLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRadioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRadioFemale)
                                        .addGap(21, 21, 21))
                                    .addComponent(firstNameTextField)
                                    .addComponent(lastNameTextField)
                                    .addComponent(ageTextField)
                                    .addComponent(affiliationTextField)
                                    .addComponent(majorTextField)
                                    .addComponent(dobTextField)
                                    .addComponent(workYearTextField))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EducationLabel)
                    .addComponent(adressLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(degreeDate1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degreeDate2Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degree2Label)
                                    .addComponent(streetln2Label)
                                    .addComponent(cityLabel)
                                    .addComponent(countryLabel)
                                    .addComponent(degree1Label)
                                    .addComponent(streetli1Label)
                                    .addComponent(schoolLabel))
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(streetln2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(cityTextField)
                                    .addComponent(countryTextField)
                                    .addComponent(streetln1TextField)
                                    .addComponent(btnRadioCitizen)
                                    .addComponent(btnRadioInternational)
                                    .addComponent(btnRadioGraduate)
                                    .addComponent(btnRadioInProgress)
                                    .addComponent(degreeDate2TextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pictureLabel1)
                            .addComponent(pictureLabel)
                            .addComponent(addButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(javaCheckBox)
                                    .addComponent(programLabel)
                                    .addComponent(cCheckBox)
                                    .addComponent(cPlusCheckBox)
                                    .addComponent(pythonCheckBox)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureLabel)
                    .addComponent(EducationLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pictureLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(programLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaCheckBox)
                        .addGap(3, 3, 3)
                        .addComponent(cCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cPlusCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pythonCheckBox)
                        .addGap(33, 33, 33)
                        .addComponent(createButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(degree1Label)
                                .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LastNameLabel)
                            .addComponent(lastNameTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexLabel)
                            .addComponent(degreeDate1Label)
                            .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRadioMale)
                            .addComponent(btnRadioFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degree2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degreeDate2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLabel)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(affiliationLabel))))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adressLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(majorLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(streetli1Label)
                                .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dobLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(streetln2Label)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(workYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cityLabel)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(workYearLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countryLabel)
                                    .addComponent(careerObjectiveStatementLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRadioCitizen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRadioInternational)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadioGraduate)
                                    .addComponent(schoolLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRadioInProgress)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioFemaleActionPerformed
        sex = btnRadioMale.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioFemaleActionPerformed

    private void btnRadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioMaleActionPerformed
        // TODO add your handling code here:
        sex = btnRadioFemale.getText();
    }//GEN-LAST:event_btnRadioMaleActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileFilter(new MyFileFilter("jpg"));
        int returnValue = fc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            name = fc.getSelectedFile().getPath();
            pictureLabel1.setIcon(new ImageIcon(name));
        }// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
         ageText=ageTextField.getText();
         workYearText=workYearTextField.getText();
        if(ageText==null||ageText.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Age can not be empty!");
        }
        else if(!rc.isNumeric(ageText))
        {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
        }
        else if(workYearText==null||workYearText.equals("")){
            JOptionPane.showMessageDialog(null, "workYear can not be empty!");
        }
        else if(!rc.isFloat(workYearText))
        {
            JOptionPane.showMessageDialog(null, "workYear must be float number or integer!");
        }
        else{
        program=java+" "+cPlus+" "+c+" "+python;
        Resume r = rc.addResume();
        r.setName(firstNameTextField.getText()+","+lastNameTextField.getText());
        r.setSex(sex);
        r.setStatus(status);
        r.setNationality(nationality);
        r.setProgram(program);
        r.setAge(Integer.parseInt(ageText));
        r.setAffiliation(affiliationTextField.getText());
        r.setMajor(majorTextField.getText());
        r.setDob(dobTextField.getText());
        r.setWorkYear(Float.parseFloat(workYearText));
        r.setCareerObjectiveStatement(careerObjectiveStatementTextArea.getText());
        r.setAddress(streetln1TextField.getText()+","+streetln2TextField.getText()+","+cityTextField.getText()+","+countryTextField.getText());
        r.setEducation(degree1TextField.getText()+","+degreeDate1TextField.getText()+","+degree2TextField.getText()+","+degreeDate2TextField.getText());
        //System.out.println(r.getAddress());
        //System.out.println(r.getEducation());
        r.setPicture(name);
        ArrayList<String> list = new ArrayList<String>();
        list.add(firstNameTextField.getText());
        list.add(lastNameTextField.getText());
        list.add(r.getSex());
        list.add(r.getStatus());
        list.add(r.getNationality());
        list.add(r.getPicture());
        list.add(r.getAffiliation());
        list.add(r.getMajor());
        list.add(r.getDob());
        list.add(r.getCareerObjectiveStatement());
        list.add(streetln1TextField.getText());
        list.add(streetln2TextField.getText());
        list.add(cityTextField.getText());
        list.add(countryTextField.getText());
        list.add(degree1TextField.getText());
        list.add(degreeDate1TextField.getText());
        list.add(degree2TextField.getText());
        list.add(degreeDate2TextField.getText());
        for(int i = 0; i<list.size(); i++){
            if(list.get(i)==null||(list.get(i)).equals("")){
                JOptionPane.showMessageDialog(null, "There must be no empty space,if there exists empty spaces the Resume can not be created(except programming skills)");
                list.clear();
                rc.deleteResume(r);
                break;
            }
        }
        
        if(!list.isEmpty()){
            JOptionPane.showMessageDialog(null,"Create Resume Successlly");
            firstNameTextField.setText("");
            lastNameTextField.setText("");
            ageTextField.setText("");
            affiliationTextField.setText("");
            majorTextField.setText("");
            dobTextField.setText("");
            workYearTextField.setText("");
            careerObjectiveStatementTextArea.setText("");
            streetln1TextField.setText("");
            streetln2TextField.setText("");
            cityTextField.setText("");
            countryTextField.setText("");
            degree1TextField.setText("");
            degreeDate1TextField.setText("");
            degree2TextField.setText("");
            degreeDate2TextField.setText("");
            btnRadioMale.setContentAreaFilled(false);
            btnRadioMale.setBorderPainted(false);
            btnRadioFemale.setContentAreaFilled(false);
            btnRadioFemale.setBorderPainted(false);
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    private void btnRadioCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioCitizenActionPerformed
        status = btnRadioCitizen.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioCitizenActionPerformed

    private void btnRadioInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioInternationalActionPerformed
        status = btnRadioInternational.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioInternationalActionPerformed

    private void btnRadioGraduateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioGraduateActionPerformed
        nationality = btnRadioGraduate.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioGraduateActionPerformed

    private void btnRadioInProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioInProgressActionPerformed
        nationality = btnRadioInProgress.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioInProgressActionPerformed

    private void javaCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_javaCheckBoxStateChanged
       if(javaCheckBox.isSelected())java=javaCheckBox.getText(); 
       else java="";// TODO add your handling code here:
    }//GEN-LAST:event_javaCheckBoxStateChanged

    private void cCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cCheckBoxStateChanged
        if(cCheckBox.isSelected())c=cCheckBox.getText();
        else c="";// TODO add your handling code here:
    }//GEN-LAST:event_cCheckBoxStateChanged

    private void cPlusCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cPlusCheckBoxStateChanged
        if(cPlusCheckBox.isSelected())cPlus=cPlusCheckBox.getText();
        else cPlus="";// TODO add your handling code here:
    }//GEN-LAST:event_cPlusCheckBoxStateChanged

    private void pythonCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pythonCheckBoxStateChanged
        if(pythonCheckBox.isSelected())python=pythonCheckBox.getText();
        else python="";// TODO add your handling code here:
    }//GEN-LAST:event_pythonCheckBoxStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EducationLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel affiliationLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup btnGroupNationality;
    private javax.swing.ButtonGroup btnGroupProgram;
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.ButtonGroup btnGroupStatus;
    private javax.swing.JRadioButton btnRadioCitizen;
    private javax.swing.JRadioButton btnRadioFemale;
    private javax.swing.JRadioButton btnRadioGraduate;
    private javax.swing.JRadioButton btnRadioInProgress;
    private javax.swing.JRadioButton btnRadioInternational;
    private javax.swing.JRadioButton btnRadioMale;
    private javax.swing.JCheckBox cCheckBox;
    private javax.swing.JCheckBox cPlusCheckBox;
    private javax.swing.JLabel careerObjectiveStatementLabel1;
    private javax.swing.JTextArea careerObjectiveStatementTextArea;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JTextField degree1TextField;
    private javax.swing.JLabel degree2Label;
    private javax.swing.JTextField degree2TextField;
    private javax.swing.JLabel degreeDate1Label;
    private javax.swing.JTextField degreeDate1TextField;
    private javax.swing.JLabel degreeDate2Label;
    private javax.swing.JTextField degreeDate2TextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox javaCheckBox;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JTextField majorTextField;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel pictureLabel1;
    private javax.swing.JLabel programLabel;
    private javax.swing.JCheckBox pythonCheckBox;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel streetli1Label;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JLabel streetln2Label;
    private javax.swing.JTextField streetln2TextField;
    private javax.swing.JLabel workYearLabel;
    private javax.swing.JTextField workYearTextField;
    // End of variables declaration//GEN-END:variables
}
