/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Data.Resume;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.util.ArrayList;
/**
 *
 * @author yyneu
 */
public class createJPanel extends javax.swing.JPanel {
     private Resume r;
     private String name;
     
    /**
     * Creates new form createJPanel
     */
    public createJPanel(Resume r) {
        initComponents();
        this.r=r;
        careerObjectiveStatementTextArea.setSelectedTextColor(Color.RED);
        careerObjectiveStatementTextArea.setLineWrap(true);        //激活自动换行功能 
        careerObjectiveStatementTextArea.setWrapStyleWord(true); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        affiliationLabel = new javax.swing.JLabel();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        careerObjectiveStatementTextArea = new javax.swing.JTextArea();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        sexTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        affiliationTextField = new javax.swing.JTextField();
        streetli1Label = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        streetln1TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        streetln2Label = new javax.swing.JLabel();
        EducationLabel = new javax.swing.JLabel();
        degree2Label = new javax.swing.JLabel();
        degreeDate1Label = new javax.swing.JLabel();
        degree1Label = new javax.swing.JLabel();
        degree1TextField = new javax.swing.JTextField();
        degreeDate1TextField = new javax.swing.JTextField();
        degree2TextField = new javax.swing.JTextField();
        degreeDate2TextField = new javax.swing.JTextField();
        degreeDate2Label = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        majorTextField = new javax.swing.JTextField();
        workYearLabel = new javax.swing.JLabel();
        workYearTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        pictureLabel1 = new javax.swing.JLabel();
        careerObjectiveStatementLabel1 = new javax.swing.JLabel();

        setToolTipText("Resume Create");

        firstNameLabel.setText("Firstname:");

        LastNameLabel.setText("Lastname:");

        sexLabel.setText("Sex:");

        ageLabel.setText("Age:");

        affiliationLabel.setText("Affiliation:");

        pictureLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pictureLabel.setText("Picture:");

        careerObjectiveStatementTextArea.setColumns(10);
        careerObjectiveStatementTextArea.setRows(20);
        jScrollPane2.setViewportView(careerObjectiveStatementTextArea);

        streetli1Label.setText("Streetln1:");

        cityLabel.setText("City:");

        countryLabel.setText("Country:");

        adressLabel.setText("Address:");

        dobLabel.setText("DOB:");

        streetln2Label.setText("Streeln2:");

        EducationLabel.setText("Education:");

        degree2Label.setText("degree2:");

        degreeDate1Label.setText("degreeDate1:");

        degree1Label.setText("degree1:");

        degreeDate2Label.setText("degreeDate2:");

        majorLabel.setText("Major:");

        workYearLabel.setText("workYear:");

        createButton.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        createButton.setText("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        pictureLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/default.jpg"))); // NOI18N

        careerObjectiveStatementLabel1.setText("CareerObjevtiveStatement:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(majorLabel)
                            .addComponent(careerObjectiveStatementLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameLabel)
                                    .addComponent(sexLabel)
                                    .addComponent(affiliationLabel)
                                    .addComponent(dobLabel)
                                    .addComponent(workYearLabel)
                                    .addComponent(ageLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sexTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(lastNameTextField)
                                        .addComponent(affiliationTextField)
                                        .addComponent(majorTextField)
                                        .addComponent(dobTextField)
                                        .addComponent(workYearTextField)))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EducationLabel)
                    .addComponent(adressLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(degreeDate1Label)
                        .addGap(12, 12, 12)
                        .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree2Label)
                            .addComponent(degreeDate2Label)
                            .addComponent(streetln2Label)
                            .addComponent(cityLabel)
                            .addComponent(countryLabel)
                            .addComponent(degree1Label)
                            .addComponent(streetli1Label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton)
                    .addComponent(pictureLabel1)
                    .addComponent(pictureLabel)
                    .addComponent(addButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureLabel)
                    .addComponent(EducationLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pictureLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(addButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel)
                            .addComponent(degree1Label)
                            .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexLabel)
                            .addComponent(sexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeDate1Label)
                            .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degree2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degreeDate2Label)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLabel)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(affiliationLabel)
                                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(majorLabel)
                            .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adressLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dobLabel)
                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetli1Label)
                                    .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(workYearLabel)
                                    .addComponent(workYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetln2Label)))
                            .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countryLabel)
                                    .addComponent(careerObjectiveStatementLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
       r.setName(firstNameTextField.getText()+","+lastNameTextField.getText());
       r.setSex(sexTextField.getText());
       r.setAge(ageTextField.getText());
       r.setAffiliation(affiliationTextField.getText());
       r.setMajor(majorTextField.getText());
       r.setDob(dobTextField.getText());
       r.setWorkYear(workYearTextField.getText());
       r.setCareerObjectiveStatement(careerObjectiveStatementTextArea.getText());
       r.setAddress(streetln1TextField.getText()+","+streetln2TextField.getText()+","+cityTextField.getText()+","+countryTextField.getText());
       r.setEducation(degree1TextField.getText()+","+degreeDate1TextField.getText()+","+degree2TextField.getText()+","+degreeDate2TextField.getText());
       //System.out.println(r.getAddress());
       //System.out.println(r.getEducation());
       r.setPicture(name);
       ArrayList<String> list = new ArrayList<String>();
       list.add(firstNameTextField.getText());
       list.add(lastNameTextField.getText());
       list.add(r.getSex());
       list.add(r.getAge());
       list.add(r.getAffiliation());
       list.add(r.getMajor());
       list.add(r.getDob());
       list.add(r.getWorkYear());
       list.add(r.getCareerObjectiveStatement());
       list.add(streetln1TextField.getText());
       list.add(streetln2TextField.getText());
       list.add(cityTextField.getText());
       list.add(countryTextField.getText());
       list.add(degree1TextField.getText());
       list.add(degreeDate1TextField.getText());
       list.add(degree2TextField.getText());
       list.add(degreeDate2TextField.getText());
       for(int i = 0; i<list.size(); i++){
       if(list.get(i)==null||(list.get(i)).equals("")){
       JOptionPane.showMessageDialog(null, "There must be no empty space,if there exists empty spaces the Resume can not be created.");
       list.clear();
       break;
}
}
       if(!list.isEmpty()){               
           JOptionPane.showMessageDialog(null,"Create Resume Successlly");
       }
       
       // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); 
        fc.setAcceptAllFileFilterUsed(false); 
        fc.setFileFilter(new MyFileFilter("jpg")); 
        int returnValue = fc.showOpenDialog(null);  
        if (returnValue == JFileChooser.APPROVE_OPTION)  
        {  
         name = fc.getSelectedFile().getPath();
         pictureLabel1.setIcon(new ImageIcon(name));  
        }// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EducationLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel affiliationLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel careerObjectiveStatementLabel1;
    private javax.swing.JTextArea careerObjectiveStatementTextArea;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JTextField degree1TextField;
    private javax.swing.JLabel degree2Label;
    private javax.swing.JTextField degree2TextField;
    private javax.swing.JLabel degreeDate1Label;
    private javax.swing.JTextField degreeDate1TextField;
    private javax.swing.JLabel degreeDate2Label;
    private javax.swing.JTextField degreeDate2TextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JTextField majorTextField;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel pictureLabel1;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField sexTextField;
    private javax.swing.JLabel streetli1Label;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JLabel streetln2Label;
    private javax.swing.JTextField streetln2TextField;
    private javax.swing.JLabel workYearLabel;
    private javax.swing.JTextField workYearTextField;
    // End of variables declaration//GEN-END:variables
}
