/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Data.Resume;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author yyneu
 */
public class viewJPanel extends javax.swing.JPanel {
private Resume r;
    /**
     * Creates new form viewJPanel
     */
    public viewJPanel(Resume r) {
        initComponents();
        careerObjectiveStatementTextArea.setSelectedTextColor(Color.RED);
        careerObjectiveStatementTextArea.setLineWrap(true);        //激活自动换行功能 
        careerObjectiveStatementTextArea.setWrapStyleWord(true); 
        displayData(r);
    }
public void displayData(Resume r){
        String str0=r.getName();
        String [] splitName = str0.split(",");
        firstNameTextField.setText(splitName[0]);
        lastNameTextField.setText(splitName[1]);
        sexTextField.setText(r.getSex());
        ageTextField.setText(r.getAge());
        affiliationTextField.setText(r.getAffiliation());
        majorTextField.setText(r.getMajor());
        dobTextField.setText(r.getDob());
        workYearTextField.setText(r.getWorkYear());
        careerObjectiveStatementTextArea.setText(r.getCareerObjectiveStatement());
        pictureLabel1.setIcon(new ImageIcon(r.getPicture()));
        String str1=r.getAddress();
        String [] splitAddress = str1.split(",");
        streetln1TextField.setText(splitAddress[0]);
        streetln2TextField.setText(splitAddress[1]);
        cityTextField.setText(splitAddress[2]);
        countryTextField.setText(splitAddress[3]);
        String str2=r.getEducation();
        String [] splitEducation = str2.split(",");
        degree1TextField.setText(splitEducation[0]);
        degreeDate1TextField.setText(splitEducation[1]);
        degree2TextField.setText(splitEducation[2]);
        degreeDate2TextField.setText(splitEducation[3]);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        affiliationTextField = new javax.swing.JTextField();
        majorTextField = new javax.swing.JTextField();
        streetli1Label = new javax.swing.JLabel();
        workYearLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        workYearTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        streetln1TextField = new javax.swing.JTextField();
        pictureLabel1 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        streetln2TextField = new javax.swing.JTextField();
        careerObjectiveStatementLabel1 = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        streetln2Label = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        EducationLabel = new javax.swing.JLabel();
        affiliationLabel = new javax.swing.JLabel();
        degree2Label = new javax.swing.JLabel();
        pictureLabel = new javax.swing.JLabel();
        degreeDate1Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        careerObjectiveStatementTextArea = new javax.swing.JTextArea();
        degree1Label = new javax.swing.JLabel();
        degree1TextField = new javax.swing.JTextField();
        degreeDate1TextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        degree2TextField = new javax.swing.JTextField();
        degreeDate2TextField = new javax.swing.JTextField();
        sexTextField = new javax.swing.JTextField();
        degreeDate2Label = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        majorLabel = new javax.swing.JLabel();

        setToolTipText("Resume View");

        streetli1Label.setText("Streetln1:");

        workYearLabel.setText("workYear:");

        cityLabel.setText("City:");

        countryLabel.setText("Country:");

        adressLabel.setText("Address:");

        pictureLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/default.jpg"))); // NOI18N

        careerObjectiveStatementLabel1.setText("CareerObjevtiveStatement:");

        dobLabel.setText("DOB:");

        LastNameLabel.setText("Lastname:");

        sexLabel.setText("Sex:");

        streetln2Label.setText("Streeln2:");

        ageLabel.setText("Age:");

        EducationLabel.setText("Education:");

        affiliationLabel.setText("Affiliation:");

        degree2Label.setText("degree2:");

        pictureLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pictureLabel.setText("Picture:");

        degreeDate1Label.setText("degreeDate1:");

        careerObjectiveStatementTextArea.setColumns(10);
        careerObjectiveStatementTextArea.setRows(20);
        jScrollPane2.setViewportView(careerObjectiveStatementTextArea);

        degree1Label.setText("degree1:");

        firstNameLabel.setText("Firstname:");

        degreeDate2Label.setText("degreeDate2:");

        majorLabel.setText("Major:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(majorLabel)
                            .addComponent(careerObjectiveStatementLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameLabel)
                                    .addComponent(sexLabel)
                                    .addComponent(affiliationLabel)
                                    .addComponent(dobLabel)
                                    .addComponent(workYearLabel)
                                    .addComponent(ageLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(affiliationTextField)
                                    .addComponent(majorTextField)
                                    .addComponent(dobTextField)
                                    .addComponent(workYearTextField)
                                    .addComponent(sexTextField)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EducationLabel)
                    .addComponent(adressLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(degreeDate1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree2Label)
                            .addComponent(degreeDate2Label)
                            .addComponent(streetln2Label)
                            .addComponent(cityLabel)
                            .addComponent(countryLabel)
                            .addComponent(degree1Label)
                            .addComponent(streetli1Label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureLabel1)
                    .addComponent(pictureLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureLabel)
                    .addComponent(EducationLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(pictureLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel)
                            .addComponent(degree1Label)
                            .addComponent(degree1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexLabel)
                            .addComponent(sexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeDate1Label)
                            .addComponent(degreeDate1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degree2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degreeDate2Label)
                                    .addComponent(degreeDate2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLabel)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(affiliationLabel)
                                    .addComponent(affiliationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(majorLabel)
                            .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adressLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dobLabel)
                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetli1Label)
                                    .addComponent(streetln2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(workYearLabel)
                                    .addComponent(workYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(streetln2Label)))
                            .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryLabel)
                            .addComponent(careerObjectiveStatementLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetln1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EducationLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel affiliationLabel;
    private javax.swing.JTextField affiliationTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel careerObjectiveStatementLabel1;
    private javax.swing.JTextArea careerObjectiveStatementTextArea;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel degree1Label;
    private javax.swing.JTextField degree1TextField;
    private javax.swing.JLabel degree2Label;
    private javax.swing.JTextField degree2TextField;
    private javax.swing.JLabel degreeDate1Label;
    private javax.swing.JTextField degreeDate1TextField;
    private javax.swing.JLabel degreeDate2Label;
    private javax.swing.JTextField degreeDate2TextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JTextField majorTextField;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel pictureLabel1;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JTextField sexTextField;
    private javax.swing.JLabel streetli1Label;
    private javax.swing.JTextField streetln1TextField;
    private javax.swing.JLabel streetln2Label;
    private javax.swing.JTextField streetln2TextField;
    private javax.swing.JLabel workYearLabel;
    private javax.swing.JTextField workYearTextField;
    // End of variables declaration//GEN-END:variables
}
