/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VendorInterface;

import Business.Product;
import Business.ProductDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yyneu
 */
public class vendorManageJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
private ProductDirectory productDirectory;
String productCatalog;
    /**
     * Creates new form vendorSelectedJPanel
     */
 
    public vendorManageJPanel(JPanel userProcessContainer, ProductDirectory productDirectory) {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.productDirectory = productDirectory;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtVendorName = new javax.swing.JTextField();
        btnSearchVendor = new javax.swing.JButton();
        btnCreateVendor = new javax.swing.JButton();
        btnRadioComputer = new javax.swing.JRadioButton();
        btnRadioPrinter = new javax.swing.JRadioButton();
        btnRadioHardwareParts = new javax.swing.JRadioButton();
        btnRadioSoftwareProducts = new javax.swing.JRadioButton();

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearchVendor.setText("Search Vendor");
        btnSearchVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVendorActionPerformed(evt);
            }
        });

        btnCreateVendor.setText("Create Vendor");
        btnCreateVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVendorActionPerformed(evt);
            }
        });

        btnRadioComputer.setText("computer");
        btnRadioComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioComputerActionPerformed(evt);
            }
        });

        btnRadioPrinter.setText("printer");
        btnRadioPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioPrinterActionPerformed(evt);
            }
        });

        btnRadioHardwareParts.setText("hardware parts");
        btnRadioHardwareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioHardwarePartsActionPerformed(evt);
            }
        });

        btnRadioSoftwareProducts.setText("software products");
        btnRadioSoftwareProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioSoftwareProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(btnRadioComputer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRadioPrinter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioHardwareParts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioSoftwareProducts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateVendor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchVendor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchVendor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateVendor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRadioComputer)
                        .addComponent(btnRadioPrinter)
                        .addComponent(btnRadioHardwareParts)
                        .addComponent(btnRadioSoftwareProducts)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVendorActionPerformed
        if(txtVendorName.getText() == null||txtVendorName.getText().equals(""))  JOptionPane.showMessageDialog(null,"Vendor Name can not be empty!",
                    "Information", JOptionPane.WARNING_MESSAGE);
        else{ 
            ArrayList<Product> result = productDirectory.searchVendorNameAccount(txtVendorName.getText());
        if(result.isEmpty()){
            JOptionPane.showMessageDialog(null,"Vendor Name you entered does not exist",
                    "Information", JOptionPane.WARNING_MESSAGE);
        }
        else{
            vendorDetailsJPanel panel = new vendorDetailsJPanel(userProcessContainer, result, productDirectory);
            userProcessContainer.add("vendorProductDetailsJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        }
    }//GEN-LAST:event_btnSearchVendorActionPerformed

    private void btnRadioComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioComputerActionPerformed
        productCatalog = btnRadioComputer.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioComputerActionPerformed

    private void btnRadioPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioPrinterActionPerformed
        productCatalog = btnRadioPrinter.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_btnRadioPrinterActionPerformed

    private void btnRadioHardwarePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioHardwarePartsActionPerformed
        productCatalog = btnRadioHardwareParts.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioHardwarePartsActionPerformed

    private void btnRadioSoftwareProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioSoftwareProductsActionPerformed
        productCatalog = btnRadioSoftwareProducts.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioSoftwareProductsActionPerformed

    private void btnCreateVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVendorActionPerformed
        if(productCatalog!=null){
        VendorCreateJPanel panel = new VendorCreateJPanel(userProcessContainer,productDirectory,productCatalog);
        userProcessContainer.add("VendorCreateJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        }
        else JOptionPane.showMessageDialog(null,"You must select a product catalog!");
    }//GEN-LAST:event_btnCreateVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateVendor;
    private javax.swing.JRadioButton btnRadioComputer;
    private javax.swing.JRadioButton btnRadioHardwareParts;
    private javax.swing.JRadioButton btnRadioPrinter;
    private javax.swing.JRadioButton btnRadioSoftwareProducts;
    private javax.swing.JButton btnSearchVendor;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
