/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VendorInterface;


import Business.Product;
import Business.ProductDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yyneu
 */
public class VendorAddProductJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ProductDirectory productDirectory;
    private String productCatalog;
    private String vendorName;
    /**
     * Creates new form CreateAccountJPanel
     */
    VendorAddProductJPanel(JPanel userProcessContainer, ProductDirectory productDirectory, String vendorName) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productDirectory = productDirectory;
        this.vendorName = vendorName;
        txtVendorName.setText(vendorName);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lalHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtVendorName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCeilingPrice = new javax.swing.JTextField();
        txtFloorPrice = new javax.swing.JTextField();
        txtBasePrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        featureJTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnRadioComputer = new javax.swing.JRadioButton();
        btnRadioPrinter = new javax.swing.JRadioButton();
        btnRadioHardwareParts = new javax.swing.JRadioButton();
        btnRadioSoftwareProducts = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        lalHeader.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        lalHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalHeader.setText("Add Product");

        jLabel1.setText("Product Name:");

        jLabel2.setText("Model Number:");

        jLabel3.setText("Vendor Name:");

        jLabel4.setText("Description:");

        txtVendorName.setEnabled(false);

        btnCreate.setText("Add Product");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("Base Price:");

        jLabel6.setText("Ceiling Price:");

        jLabel7.setText("Floor Price:");

        featureJTextArea.setColumns(20);
        featureJTextArea.setLineWrap(true);
        featureJTextArea.setRows(5);
        featureJTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(featureJTextArea);

        jLabel8.setText("Features and Benefits:");

        btnRadioComputer.setText("computer");
        btnRadioComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioComputerActionPerformed(evt);
            }
        });

        btnRadioPrinter.setText("printer");
        btnRadioPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioPrinterActionPerformed(evt);
            }
        });

        btnRadioHardwareParts.setText("hardware parts");
        btnRadioHardwareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioHardwarePartsActionPerformed(evt);
            }
        });

        btnRadioSoftwareProducts.setText("software products");
        btnRadioSoftwareProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioSoftwareProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lalHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBasePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnRadioComputer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioPrinter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioHardwareParts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadioSoftwareProducts)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lalHeader)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCeilingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFloorPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadioComputer)
                    .addComponent(btnRadioPrinter)
                    .addComponent(btnRadioHardwareParts)
                    .addComponent(btnRadioSoftwareProducts))
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String basePrice = txtBasePrice.getText();
        String floorPrice = txtFloorPrice.getText();
        String ceilingPrice = txtCeilingPrice.getText();
        if(!productDirectory.isDouble(basePrice))
        {
            JOptionPane.showMessageDialog(null, "Base Price must be a number!");
        }
        else if(!productDirectory.isDouble(floorPrice))
        {
            JOptionPane.showMessageDialog(null, "Floor Price must be a number!");
        }
        else if(!productDirectory.isDouble(ceilingPrice))
        {
            JOptionPane.showMessageDialog(null, "Ceiling Price must be a number!");
        }
        else{
        String productName = txtProductName.getText();
        String modelNumber = txtModelNumber.getText();
        String description = txtDescription.getText();
       
        String feature = featureJTextArea.getText();
        ArrayList<String> list = new ArrayList<String>();
        list.add(productName);
        list.add(modelNumber);
        list.add(description);
        list.add(productCatalog);
        list.add(txtBasePrice.getText());
        list.add(txtCeilingPrice.getText());
        list.add(txtFloorPrice.getText());
        list.add(feature);
        for(int i = 0; i<list.size(); i++){
        if(list.get(i)==null||(list.get(i)).equals("")){
        JOptionPane.showMessageDialog(null, "There must be no empty space,if there exists empty spaces the Product can not be created.");
        list.clear();
        break;
        }
            }
        if(!list.isEmpty()){
        Product account = productDirectory.addProduct();
        account.setProductCatalog(productCatalog);
        account.setProductName(productName);
        account.setModelNumber(modelNumber);
        account.setDescription(description);
        account.setVendorName(vendorName);
        account.setBasePrice(Float.parseFloat(basePrice));
        account.setCeilingPrice(Float.parseFloat(ceilingPrice));
        account.setFloorPrice(Float.parseFloat(floorPrice));
        account.setFeature(feature);
        
        JOptionPane.showMessageDialog(null, "Account created successfully");
        }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRadioComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioComputerActionPerformed
        productCatalog = btnRadioComputer.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioComputerActionPerformed

    private void btnRadioPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioPrinterActionPerformed
        productCatalog = btnRadioPrinter.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_btnRadioPrinterActionPerformed

    private void btnRadioHardwarePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioHardwarePartsActionPerformed
        productCatalog = btnRadioHardwareParts.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioHardwarePartsActionPerformed

    private void btnRadioSoftwareProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioSoftwareProductsActionPerformed
        productCatalog = btnRadioSoftwareProducts.getText();// TODO add your handling code here:
    }//GEN-LAST:event_btnRadioSoftwareProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JRadioButton btnRadioComputer;
    private javax.swing.JRadioButton btnRadioHardwareParts;
    private javax.swing.JRadioButton btnRadioPrinter;
    private javax.swing.JRadioButton btnRadioSoftwareProducts;
    private javax.swing.JTextArea featureJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lalHeader;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtCeilingPrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFloorPrice;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
